# Usa la imagen base de Python 3.10.5
FROM python:3.10.5

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de requisitos e instala las dependencias
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Instala el cliente de MySQL (opcional)
RUN apt-get update && apt-get install -y default-mysql-client

# Copia el resto del código fuente al directorio de trabajo
COPY . .

# Comando por defecto para ejecutar el servidor web en el contenedor
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
